### ISSUE TITLE
Auth error storage.bucket.get

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [paulaaronfrank/mp3-to-txt#1]
i am getting this error 

google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/mp3-to-speech-audio?projection=noAcl: mp3-to-txt-final@mp-to-ext-final.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.

tried adding the storage.admin role but nothing changed

**Comment by paulaaronfrank** [comment]
This sounds to me like one of the following, but If not, I would require more detail about your setup.

1. Option: [_"Every bucket name must be globally unique."_](https://cloud.google.com/storage/docs/naming-buckets)
2. Option: [Use service account credentials to authenticate.](https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-python)
3. Explicitly add the Service account to the storage bucket.
